apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: droneservice-orderer1
  namespace: droneservice-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: droneservice-orderer1
  chart:
    git: https://github.com/MChorfa/blockchain-automation-framework.git
    ref: local
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: droneservice-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.0
        alpineutils: hyperledgerlabs/alpine-utils:1.0

    orderer:
      name: orderer1
      loglevel: info
      localmspid: droneserviceMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: kafka

    storage:
      storageclassname: droneservicesc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.2.121:8200
      role: vault-role
      authpath: localdroneservice-net-auth
      secretprefix: secret/crypto/ordererOrganizations/droneservice-net/orderers/orderer1.droneservice-net
      imagesecretname: regcred
      serviceaccountname: vault-auth
    kafka:
      readinesscheckinterval: 10
      readinessthreshold: 10
      brokers:
      - kafka-0.broker.droneservice-net.svc.cluster.local:9092
      - kafka-1.broker.droneservice-net.svc.cluster.local:9092
      - kafka-2.broker.droneservice-net.svc.cluster.local:9092

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIH2SEiPVfOdqJlt/zy6XJtli+FLLABGAiT9Kml1+pbpzEtNOCtBOCs1OCngKWggBEAEaBgit
      heqGBiIKc3lzY2hhbm5lbCpANjgyZjhhOTAwMjg0NTdhMmJlODQ2NjJhMzg0NGQxODAzNGUzMTFi
      ZTliM2RhYTJhNWZiZTlmODgzZWNkOWQ5MxIaEhhdgIqzrSPPpPR9U5NG6c6LF2CsNXxXvL8S0E0K
      zU0Syk0ShDAKC0NvbnNvcnRpdW1zEvQvEqkvChZEcm9uZVNlcnZpY2VDb25zb3J0aXVtEo4vErAu
      CgtjdXN0b21lck1TUBKgLhq4LAoDTVNQErAsEqUsEqIsCgtjdXN0b21lck1TUBLsBS0tLS0tQkVH
      SU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCL0RDQ0FhS2dBd0lCQWdJVUVhbmx6RXE3ZGJxcjlvUmxI
      bUp0N3ZxY05ZQXdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZC
      QWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFoRGRYTjBi
      MjFsY2pFWU1CWUdBMVVFQXd3UFkyRXVZM1Z6ZEc5dFpYSXRibVYwTUI0WApEVEl4TURZeU9UQXhN
      VFF5TkZvWERUSTBNRFF4T0RBeE1UUXlORm93WERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOCkJnTlZC
      QWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm9NUkV3RHdZRFZRUUtEQWhEZFhOMGIy
      MWwKY2pFWU1CWUdBMVVFQXd3UFkyRXVZM1Z6ZEc5dFpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FR
      WUlLb1pJemowRApBUWNEUWdBRTlqdVJWb0tKVUhmWlBBMEZXL2lMZi93QW5YY3NHRTEveUNDRVRq
      WkMxNU1kRlJOa0lnMXhZOHUvCm11eVBkeVFlYnBYK1U3ZXZaS0E4QXpXS3ZTVFcxcU5DTUVBd0R3
      WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZD
      b2p5WU9ZcjNLTGVoSUM1ZGMrblBQU0VKSndNQW9HQ0NxRwpTTTQ5QkFNQ0EwZ0FNRVVDSURPSnhB
      bFhNcTVBTEUrckxJL1MybHdvb3NVcC9PRG9uZGtaUnFobHZ5dDZBaUVBCmdaaVNrenBOMGFJT1dx
      ejVQNnBKRlVRbnIzVnJ4SXJQSEExaC91ZXJDUDQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0i
      uQgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzh6Q0NBcHFnQXdJQkFnSVVhY1QxdkpY
      a1FwMkhKNmhRYkpPN0h2b2NhdTh3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUTBn
      eER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SRXdEd1lEVlFR
      S0RBaERkWE4wYjIxbGNqRVlNQllHQTFVRUF3d1BZMkV1WTNWemRHOXRaWEl0Ym1WME1CNFgKRFRJ
      eE1EWXlPVEF4TVRnd01Gb1hEVEl5TURZeU9UQXhNak13TUZvd2VqRUxNQWtHQTFVRUJoTUNRMGd4
      R2pBWQpCZ05WQkFjVEVUUTNMak00THpndU5UUXZXblZ5YVdOb01SRXdEd1lEVlFRS0V3aERkWE4w
      YjIxbGNqRWZNQXdHCkExVUVDeE1GWVdSdGFXNHdEd1lEVlFRTEV3aGpkWE4wYjIxbGNqRWJNQmtH
      QTFVRUF3d1NRV1J0YVc1QVkzVnoKZEc5dFpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJ
      emowREFRY0RRZ0FFQ0puNlJXa21wYWN5T04vNgpucnQydnkwK0tqMU1mVXJDc3pQQmV4Z0pDT0Nz
      QSt3Nm5YWEpaL3BMelV6eWxuNStJK2tJeDJqWmpoaTk3R3RZCmRkNEp1cU9DQVJvd2dnRVdNQTRH
      QTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWQKRGdRV0JCU0hzdUpE
      K3F1MExPdDl6OUl5a3kxTGpvbHZTVEFmQmdOVkhTTUVHREFXZ0JRcUk4bURtSzl5aTNvUwpBdVhY
      UHB6ejBoQ1NjREFrQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kwM09EZGlOR1k1Wm1Oa0xXNTRj
      M0Z5Ck1JR1BCZ2dxQXdRRkJnY0lBUVNCZ25zaVlYUjBjbk1pT25zaVlXSmhZeTVwYm1sMElqb2lk
      SEoxWlNJc0ltRmsKYldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaVkzVnpk
      Rzl0WlhJaUxDSm9aaTVGYm5KdgpiR3h0Wlc1MFNVUWlPaUpCWkcxcGJrQmpkWE4wYjIxbGNpMXVa
      WFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpCmZYMHdDZ1lJS29aSXpqMEVBd0lEUndBd1JBSWdl
      eURsQmVCZTh2akpUUHNWRkhvdlMweVY5TkdHUW1Hb2JkeTAKdmR2RDNkSUNJQlBDS0gxUGs2TWho
      b1d5RlZ1VVFNdGp1S3VEd0YvUGJWMzAwUTBrakpVZgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
      Qg4KBFNIQTISBlNIQTI1NkrsBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCL0RDQ0Fh
      S2dBd0lCQWdJVUVhbmx6RXE3ZGJxcjlvUmxIbUp0N3ZxY05ZQXdDZ1lJS29aSXpqMEVBd0l3ClhE
      RUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25W
      eWFXTm8KTVJFd0R3WURWUVFLREFoRGRYTjBiMjFsY2pFWU1CWUdBMVVFQXd3UFkyRXVZM1Z6ZEc5
      dFpYSXRibVYwTUI0WApEVEl4TURZeU9UQXhNVFF5TkZvWERUSTBNRFF4T0RBeE1UUXlORm93WERF
      TE1Ba0dBMVVFQmhNQ1EwZ3hEekFOCkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25W
      eWFXTm9NUkV3RHdZRFZRUUtEQWhEZFhOMGIyMWwKY2pFWU1CWUdBMVVFQXd3UFkyRXVZM1Z6ZEc5
      dFpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRTlqdVJWb0tKVUhm
      WlBBMEZXL2lMZi93QW5YY3NHRTEveUNDRVRqWkMxNU1kRlJOa0lnMXhZOHUvCm11eVBkeVFlYnBY
      K1U3ZXZaS0E4QXpXS3ZTVFcxcU5DTUVBd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlYKSFE4
      QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZDb2p5WU9ZcjNLTGVoSUM1ZGMrblBQU0VKSndNQW9H
      Q0NxRwpTTTQ5QkFNQ0EwZ0FNRVVDSURPSnhBbFhNcTVBTEUrckxJL1MybHdvb3NVcC9PRG9uZGta
      UnFobHZ5dDZBaUVBCmdaaVNrenBOMGFJT1dxejVQNnBKRlVRbnIzVnJ4SXJQSEExaC91ZXJDUDQ9
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS1a6BcIARL3BQrsBS0tLS0tQkVHSU4gQ0VSVElGSUNB
      VEUtLS0tLQpNSUlCL0RDQ0FhS2dBd0lCQWdJVUVhbmx6RXE3ZGJxcjlvUmxIbUp0N3ZxY05ZQXdD
      Z1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGph
      REVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFoRGRYTjBiMjFsY2pFWU1CWUdB
      MVVFQXd3UFkyRXVZM1Z6ZEc5dFpYSXRibVYwTUI0WApEVEl4TURZeU9UQXhNVFF5TkZvWERUSTBN
      RFF4T0RBeE1UUXlORm93WERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOCkJnTlZCQWdNQmxwMWNtbGph
      REVQTUEwR0ExVUVCd3dHV25WeWFXTm9NUkV3RHdZRFZRUUtEQWhEZFhOMGIyMWwKY2pFWU1CWUdB
      MVVFQXd3UFkyRXVZM1Z6ZEc5dFpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApB
      UWNEUWdBRTlqdVJWb0tKVUhmWlBBMEZXL2lMZi93QW5YY3NHRTEveUNDRVRqWkMxNU1kRlJOa0ln
      MXhZOHUvCm11eVBkeVFlYnBYK1U3ZXZaS0E4QXpXS3ZTVFcxcU5DTUVBd0R3WURWUjBUQVFIL0JB
      VXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZDb2p5WU9ZcjNLTGVo
      SUM1ZGMrblBQU0VKSndNQW9HQ0NxRwpTTTQ5QkFNQ0EwZ0FNRVVDSURPSnhBbFhNcTVBTEUrckxJ
      L1MybHdvb3NVcC9PRG9uZGtaUnFobHZ5dDZBaUVBCmdaaVNrenBOMGFJT1dxejVQNnBKRlVRbnIz
      VnJ4SXJQSEExaC91ZXJDUDQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0SBmNsaWVudBr1BQrs
      BS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCL0RDQ0FhS2dBd0lCQWdJVUVhbmx6RXE3
      ZGJxcjlvUmxIbUp0N3ZxY05ZQXdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4
      RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJFd0R3WURWUVFL
      REFoRGRYTjBiMjFsY2pFWU1CWUdBMVVFQXd3UFkyRXVZM1Z6ZEc5dFpYSXRibVYwTUI0WApEVEl4
      TURZeU9UQXhNVFF5TkZvWERUSTBNRFF4T0RBeE1UUXlORm93WERFTE1Ba0dBMVVFQmhNQ1EwZ3hE
      ekFOCkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm9NUkV3RHdZRFZRUUtE
      QWhEZFhOMGIyMWwKY2pFWU1CWUdBMVVFQXd3UFkyRXVZM1Z6ZEc5dFpYSXRibVYwTUZrd0V3WUhL
      b1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRTlqdVJWb0tKVUhmWlBBMEZXL2lMZi93QW5YY3NH
      RTEveUNDRVRqWkMxNU1kRlJOa0lnMXhZOHUvCm11eVBkeVFlYnBYK1U3ZXZaS0E4QXpXS3ZTVFcx
      cU5DTUVBd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURW
      UjBPQkJZRUZDb2p5WU9ZcjNLTGVoSUM1ZGMrblBQU0VKSndNQW9HQ0NxRwpTTTQ5QkFNQ0EwZ0FN
      RVVDSURPSnhBbFhNcTVBTEUrckxJL1MybHdvb3NVcC9PRG9uZGtaUnFobHZ5dDZBaUVBCmdaaVNr
      enBOMGFJT1dxejVQNnBKRlVRbnIzVnJ4SXJQSEExaC91ZXJDUDQ9Ci0tLS0tRU5EIENFUlRJRklD
      QVRFLS0tLS0SBHBlZXIi9gUK7AUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQi9EQ0NB
      YUtnQXdJQkFnSVVFYW5sekVxN2RicXI5b1JsSG1KdDd2cWNOWUF3Q2dZSUtvWkl6ajBFQXdJdwpY
      REVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1du
      VnlhV05vCk1SRXdEd1lEVlFRS0RBaERkWE4wYjIxbGNqRVlNQllHQTFVRUF3d1BZMkV1WTNWemRH
      OXRaWEl0Ym1WME1CNFgKRFRJeE1EWXlPVEF4TVRReU5Gb1hEVEkwTURReE9EQXhNVFF5TkZvd1hE
      RUxNQWtHQTFVRUJoTUNRMGd4RHpBTgpCZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1du
      VnlhV05vTVJFd0R3WURWUVFLREFoRGRYTjBiMjFsCmNqRVlNQllHQTFVRUF3d1BZMkV1WTNWemRH
      OXRaWEl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMEQKQVFjRFFnQUU5anVSVm9LSlVI
      ZlpQQTBGVy9pTGYvd0FuWGNzR0UxL3lDQ0VUalpDMTVNZEZSTmtJZzF4WTh1LwptdXlQZHlRZWJw
      WCtVN2V2WktBOEF6V0t2U1RXMXFOQ01FQXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WCkhR
      OEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGQ29qeVlPWXIzS0xlaElDNWRjK25QUFNFSkp3TUFv
      R0NDcUcKU000OUJBTUNBMGdBTUVVQ0lET0p4QWxYTXE1QUxFK3JMSS9TMmx3b29zVXAvT0RvbmRr
      WlJxaGx2eXQ2QWlFQQpnWmlTa3pwTjBhSU9XcXo1UDZwSkZVUW5yM1ZyeElyUEhBMWgvdWVyQ1A0
      PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tEgVhZG1pbir4BQrsBS0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlCL0RDQ0FhS2dBd0lCQWdJVUVhbmx6RXE3ZGJxcjlvUmxIbUp0N3ZxY05Z
      QXdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNt
      bGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFoRGRYTjBiMjFsY2pFWU1C
      WUdBMVVFQXd3UFkyRXVZM1Z6ZEc5dFpYSXRibVYwTUI0WApEVEl4TURZeU9UQXhNVFF5TkZvWERU
      STBNRFF4T0RBeE1UUXlORm93WERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOCkJnTlZCQWdNQmxwMWNt
      bGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm9NUkV3RHdZRFZRUUtEQWhEZFhOMGIyMWwKY2pFWU1C
      WUdBMVVFQXd3UFkyRXVZM1Z6ZEc5dFpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemow
      RApBUWNEUWdBRTlqdVJWb0tKVUhmWlBBMEZXL2lMZi93QW5YY3NHRTEveUNDRVRqWkMxNU1kRlJO
      a0lnMXhZOHUvCm11eVBkeVFlYnBYK1U3ZXZaS0E4QXpXS3ZTVFcxcU5DTUVBd0R3WURWUjBUQVFI
      L0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZDb2p5WU9ZcjNL
      TGVoSUM1ZGMrblBQU0VKSndNQW9HQ0NxRwpTTTQ5QkFNQ0EwZ0FNRVVDSURPSnhBbFhNcTVBTEUr
      ckxJL1MybHdvb3NVcC9PRG9uZGtaUnFobHZ5dDZBaUVBCmdaaVNrenBOMGFJT1dxejVQNnBKRlVR
      bnIzVnJ4SXJQSEExaC91ZXJDUDQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0SB29yZGVyZXIa
      BkFkbWlucyI1CgZBZG1pbnMSKxIhCAESHRIIEgYIARICCAAaERIPCgtjdXN0b21lck1TUBABGgZB
      ZG1pbnMiOAoLRW5kb3JzZW1lbnQSKRIfCAESGxIIEgYIARICCAAaDxINCgtjdXN0b21lck1TUBoG
      QWRtaW5zIjQKB1JlYWRlcnMSKRIfCAESGxIIEgYIARICCAAaDxINCgtjdXN0b21lck1TUBoGQWRt
      aW5zIjQKB1dyaXRlcnMSKRIfCAESGxIIEgYIARICCAAaDxINCgtjdXN0b21lck1TUBoGQWRtaW5z
      KgZBZG1pbnMaQAoVQ2hhbm5lbENyZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5u
      ZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggI
      ARIEEgISABoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5z
      Ev4aCgdPcmRlcmVyEvIaEtkWCg9kcm9uZXNlcnZpY2VNU1ASxRYazRQKA01TUBLFFBK6FBK3FAoP
      ZHJvbmVzZXJ2aWNlTVNQEvQFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBekNDQWFp
      Z0F3SUJBZ0lVSVpIV1dHNUs2T2x4a1R4dmpXaHlDcnpYQXU0d0NnWUlLb1pJemowRUF3SXcKWHpF
      TE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1
      Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnd3R2dZRFZRUUREQk5qWVM1a2NtOXVaWE5s
      Y25acFkyVXRibVYwCk1CNFhEVEl4TURZeU9UQXhNVFF4T1ZvWERUSTBNRFF4T0RBeE1UUXhPVm93
      WHpFTE1Ba0dBMVVFQmhNQ1IwSXgKRHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dH
      VEc5dVpHOXVNUkF3RGdZRFZRUUtEQWRQY21SbApjbVZ5TVJ3d0dnWURWUVFEREJOallTNWtjbTl1
      WlhObGNuWnBZMlV0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJCktvWkl6ajBEQVFjRFFnQUU3ejFW
      a1dLUVVrY3psTHVCaFk2ODNLUTREdG9tSzhaRFNrRElkbDUwTSs5MVNVZ2wKbnU5S1JkM3lSL2R2
      cTRPSFNQb1BRbHZkS3psN3dDS0c2bEZnY3FOQ01FQXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFP
      QmdOVkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGRWFJRVd2SUJKTEllZU1aSEp0Tk90dkZ5
      V2tECk1Bb0dDQ3FHU000OUJBTUNBMGtBTUVZQ0lRQ3pOcllRZjJwcXgxUjdUU3hsOFkvVTlSdDFi
      TnJtWTNBd1ZFQmQKanA0QXh3SWhBTmZqVHRsQWVKQnJLaExpZG93ZGdJSVZlcEhPZEtQRTAyUjZP
      cHFyQkVBbwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tIqUILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM1RENDQW91Z0F3SUJBZ0lVRjlWRU4zNWZUTWIwbFpoV3ZZOTY5NVQrQkVrd0Nn
      WUlLb1pJemowRUF3SXcKWHpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnd3R2dZRFZR
      UUREQk5qWVM1a2NtOXVaWE5sY25acFkyVXRibVYwCk1CNFhEVEl4TURZeU9UQXhNVGd3TUZvWERU
      SXlNRFl5T1RBeE1qTXdNRm93YlRFTE1Ba0dBMVVFQmhNQ1IwSXgKR3pBWkJnTlZCQWNURWpVeExq
      VXdMeTB3TGpFekwweHZibVJ2YmpFUU1BNEdBMVVFQ2hNSFQzSmtaWEpsY2pFTwpNQXdHQTFVRUN4
      TUZZV1J0YVc0eEh6QWRCZ05WQkFNTUZrRmtiV2x1UUdSeWIyNWxjMlZ5ZG1salpTMXVaWFF3CldU
      QVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFSVkdEcERwOHFnNXloeEF6WDRCMGhGOFky
      b05CelQKakRFNHRJcnZnbCtsSEZUTTZ4alFXR1JESW5ZV1lWUStBeVNDN3lvS0k3b3ArSXQ2ajRk
      VldQTDZvNElCRlRDQwpBUkV3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FDTUFB
      d0hRWURWUjBPQkJZRUZQNDBnRkZRClVxZlpsZldCN1I2bytsUTNuMDF4TUI4R0ExVWRJd1FZTUJh
      QUZFYUlFV3ZJQkpMSWVlTVpISnROT3R2RnlXa0QKTUNRR0ExVWRFUVFkTUJ1Q0dXTmhMWFJ2YjJ4
      ekxUYzROMkkwWmpsbVkyUXRjSFJzZDI0d2dZb0dDQ29EQkFVRwpCd2dCQkg1N0ltRjBkSEp6SWpw
      N0ltRmlZV011YVc1cGRDSTZJblJ5ZFdVaUxDSmhaRzFwYmlJNkluUnlkV1VpCkxDSm9aaTVCWm1a
      cGJHbGhkR2x2YmlJNklpSXNJbWhtTGtWdWNtOXNiRzFsYm5SSlJDSTZJa0ZrYldsdVFHUnkKYjI1
      bGMyVnlkbWxqWlMxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGlmWDB3Q2dZSUtvWkl6ajBF
      QXdJRApSd0F3UkFJZ1RFOWtVVlRudFM4Q0Q5N1RmZXhEdEFnN3RVUE9LNTVyUXdzbDRTdDdYb2tD
      SUNwZWNXdTZEZ2NBCkVSWWZLV294SWJ2dWg1NE96R3pDdlV4RHRxK1VNUUM0Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS1CDgoEU0hBMhIGU0hBMjU2SvQFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0t
      LS0tCk1JSUNBekNDQWFpZ0F3SUJBZ0lVSVpIV1dHNUs2T2x4a1R4dmpXaHlDcnpYQXU0d0NnWUlL
      b1pJemowRUF3SXcKWHpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBN
      QTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnd3R2dZRFZRUURE
      Qk5qWVM1a2NtOXVaWE5sY25acFkyVXRibVYwCk1CNFhEVEl4TURZeU9UQXhNVFF4T1ZvWERUSTBN
      RFF4T0RBeE1UUXhPVm93WHpFTE1Ba0dBMVVFQmhNQ1IwSXgKRHpBTkJnTlZCQWdNQmt4dmJtUnZi
      akVQTUEwR0ExVUVCd3dHVEc5dVpHOXVNUkF3RGdZRFZRUUtEQWRQY21SbApjbVZ5TVJ3d0dnWURW
      UVFEREJOallTNWtjbTl1WlhObGNuWnBZMlV0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJCktvWkl6
      ajBEQVFjRFFnQUU3ejFWa1dLUVVrY3psTHVCaFk2ODNLUTREdG9tSzhaRFNrRElkbDUwTSs5MVNV
      Z2wKbnU5S1JkM3lSL2R2cTRPSFNQb1BRbHZkS3psN3dDS0c2bEZnY3FOQ01FQXdEd1lEVlIwVEFR
      SC9CQVV3QXdFQgovekFPQmdOVkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGRWFJRVd2SUJK
      TEllZU1aSEp0Tk90dkZ5V2tECk1Bb0dDQ3FHU000OUJBTUNBMGtBTUVZQ0lRQ3pOcllRZjJwcXgx
      UjdUU3hsOFkvVTlSdDFiTnJtWTNBd1ZFQmQKanA0QXh3SWhBTmZqVHRsQWVKQnJLaExpZG93ZGdJ
      SVZlcEhPZEtQRTAyUjZPcHFyQkVBbwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tGgZBZG1pbnMi
      OAoHV3JpdGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD2Ryb25lc2VydmljZU1TUBoGQWRtaW5z
      IjkKBkFkbWlucxIvEiUIARIhEggSBggBEgIIABoVEhMKD2Ryb25lc2VydmljZU1TUBABGgZBZG1p
      bnMiPAoLRW5kb3JzZW1lbnQSLRIjCAESHxIIEgYIARICCAAaExIRCg9kcm9uZXNlcnZpY2VNU1Aa
      BkFkbWlucyI4CgdSZWFkZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPZHJvbmVzZXJ2aWNlTVNQ
      GgZBZG1pbnMqBkFkbWlucxoiCg1Db25zZW5zdXNUeXBlEhESBwoFa2Fma2EaBkFkbWlucxoiCglC
      YXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucxoeCgxCYXRjaFRpbWVvdXQSDhIECgIycxoG
      QWRtaW5zGh8KE0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRtaW5zGiQKDENhcGFiaWxpdGllcxIU
      EgoKCAoEVjJfMBIAGgZBZG1pbnMaxAEKDEthZmthQnJva2VycxKzARKoAQo2a2Fma2EtMC5icm9r
      ZXIuZHJvbmVzZXJ2aWNlLW5ldC5zdmMuY2x1c3Rlci5sb2NhbDo5MDkyCjZrYWZrYS0xLmJyb2tl
      ci5kcm9uZXNlcnZpY2UtbmV0LnN2Yy5jbHVzdGVyLmxvY2FsOjkwOTIKNmthZmthLTIuYnJva2Vy
      LmRyb25lc2VydmljZS1uZXQuc3ZjLmNsdXN0ZXIubG9jYWw6OTA5MhoGQWRtaW5zIiIKBkFkbWlu
      cxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIioKD0Jsb2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdX
      cml0ZXJzGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3Jp
      dGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFkbWlucxokCgxDYXBhYmlsaXRpZXMSFBIK
      CggKBFYyXzASABoGQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0SEhIICgZTSEEyNTYaBkFkbWlu
      cxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhASBgj/////DxoGQWRtaW5zGk8KEE9yZGVy
      ZXJBZGRyZXNzZXMSOxIgCh5vcmRlcmVyMS5kcm9uZXNlcnZpY2UtbmV0OjcwNTAaFy9DaGFubmVs
      L09yZGVyZXIvQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFk
      bWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVy
      cxoGQWRtaW5zKgZBZG1pbnMaDgoECgIKAAoACgAKAAoA
