apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: droneservice-orderer1
  namespace: droneservice-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: droneservice-orderer1
  chart:
    git: https://github.com/MChorfa/blockchain-automation-framework.git
    ref: local-dev
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: droneservice-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: hyperledgerlabs/alpine-utils:1.0

    orderer:
      name: orderer1
      loglevel: info
      localmspid: droneserviceMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: kafka

    storage:
      storageclassname: droneservicesc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.2.121:8200
      role: vault-role
      authpath: localdroneservice-net-auth
      secretprefix: secret/crypto/ordererOrganizations/droneservice-net/orderers/orderer1.droneservice-net
      imagesecretname: regcred
      serviceaccountname: vault-auth
    kafka:
      readinesscheckinterval: 10
      readinessthreshold: 10
      brokers:
      - kafka-0.broker.droneservice-net.svc.cluster.local:9092
      - kafka-1.broker.droneservice-net.svc.cluster.local:9092
      - kafka-2.broker.droneservice-net.svc.cluster.local:9092

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIMMWmUeg1bar1e5Yxmdes2CwkP2icfIuleRlXbNl3jH8EtdOCtROCtFOCngKWggBEAEaBgjm
      zOiGBiIKc3lzY2hhbm5lbCpAMGNjZmRjMmI5ZWFhY2Q3YThiMWYwOTNkNzYyZGQ2YTcwNDM0ZTNk
      NTA2N2RhOGEyODAzYjQwYmFiMTQ3NGEwYhIaEhhgppr1q5rJ9ctZJUpuYcwviabU+cCDnJkS1E0K
      0U0Szk0S/hoKB09yZGVyZXIS8hoS2RYKD2Ryb25lc2VydmljZU1TUBLFFhrNFAoDTVNQEsUUEroU
      ErcUCg9kcm9uZXNlcnZpY2VNU1AS9AUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0F6
      Q0NBYWlnQXdJQkFnSVVPL3k3eno0ZWJBVVpRcUUyTm5Xb3hhaEsvYlV3Q2dZSUtvWkl6ajBFQXdJ
      dwpYekVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3
      R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sd3dHZ1lEVlFRRERCTmpZUzVrY205
      dVpYTmxjblpwWTJVdGJtVjAKTUI0WERUSXhNRFl5T0RFNU1qSXlNMW9YRFRJME1EUXhOekU1TWpJ
      eU0xb3dYekVMTUFrR0ExVUVCaE1DUjBJeApEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFV
      RUJ3d0dURzl1Wkc5dU1SQXdEZ1lEVlFRS0RBZFBjbVJsCmNtVnlNUnd3R2dZRFZRUUREQk5qWVM1
      a2NtOXVaWE5sY25acFkyVXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUkKS29aSXpqMERBUWNEUWdB
      RU1WbVA0U2hselVIQ3dma0FKKzNvZUFULy83RGZtVlRJQThIdi92NmQ5SUs3eVZZaQpZUCtNb0JW
      WkVVTU1EdENYU3YvWVBMYXJpeVRPMThacEdYaUR1YU5DTUVBd0R3WURWUjBUQVFIL0JBVXdBd0VC
      Ci96QU9CZ05WSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZHczZoWVY0bmgvWmRvSlNQNmFX
      M010anlaeEEKTUFvR0NDcUdTTTQ5QkFNQ0Ewa0FNRVlDSVFDQzF3REFhU2liZHRVSitRT3luOWFt
      b1hwL1o0V0tIemZQbTNmZAp1VU5iYWdJaEFMYThjMGcvMFZSdFhGSVZ2ZDlQZVZML25YZk5ZaW9D
      Y0xIdE9TSWcxNFZZCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0ipQgtLS0tLUJFR0lOIENFUlRJ
      RklDQVRFLS0tLS0KTUlJQzVEQ0NBb3VnQXdJQkFnSVVGUHA3MjZLc1BkWnZVb2hOaDZIaHFGLzVZ
      bE13Q2dZSUtvWkl6ajBFQXdJdwpYekVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZi
      bVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sd3dH
      Z1lEVlFRRERCTmpZUzVrY205dVpYTmxjblpwWTJVdGJtVjAKTUI0WERUSXhNRFl5T0RFNU1qVXdN
      Rm9YRFRJeU1EWXlPREU1TXpBd01Gb3diVEVMTUFrR0ExVUVCaE1DUjBJeApHekFaQmdOVkJBY1RF
      alV4TGpVd0x5MHdMakV6TDB4dmJtUnZiakVRTUE0R0ExVUVDaE1IVDNKa1pYSmxjakVPCk1Bd0dB
      MVVFQ3hNRllXUnRhVzR4SHpBZEJnTlZCQU1NRmtGa2JXbHVRR1J5YjI1bGMyVnlkbWxqWlMxdVpY
      UXcKV1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVROU0NZaHcxWlZmVGwyUUMwS1p6
      bjdQbFBsN2RENgpTc0F4cDlRYU9nNmVDSkZwZ1VIbTEwcnFsSTJEeU5ZaDJkOUhTRUE4UWRqWkxE
      TDg1dktnZmx3V280SUJGVENDCkFSRXdEZ1lEVlIwUEFRSC9CQVFEQWdlQU1Bd0dBMVVkRXdFQi93
      UUNNQUF3SFFZRFZSME9CQllFRkZLcDZvcDIKY0lpV0Y4TE5oMThUZDdvaUl3TEdNQjhHQTFVZEl3
      UVlNQmFBRkdzNmhZVjRuaC9aZG9KU1A2YVczTXRqeVp4QQpNQ1FHQTFVZEVRUWRNQnVDR1dOaExY
      UnZiMnh6TFRjNE4ySTBaamxtWTJRdFlqZ3lNbVl3Z1lvR0NDb0RCQVVHCkJ3Z0JCSDU3SW1GMGRI
      SnpJanA3SW1GaVlXTXVhVzVwZENJNkluUnlkV1VpTENKaFpHMXBiaUk2SW5SeWRXVWkKTENKb1pp
      NUJabVpwYkdsaGRHbHZiaUk2SWlJc0ltaG1Ma1Z1Y205c2JHMWxiblJKUkNJNklrRmtiV2x1UUdS
      eQpiMjVsYzJWeWRtbGpaUzF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29a
      SXpqMEVBd0lEClJ3QXdSQUlnSU9zS3hYY05DcEQyY0R6TFFjRVJaY21oUTVJL0xmdjZNM3h1ZHFk
      VVhWNENJQnhjUnpLTG1GSHAKYk1DR0cwQTZPRHpwUmszTG5xSDJkcW9qSWREU2hqYlkKLS0tLS1F
      TkQgQ0VSVElGSUNBVEUtLS0tLUIOCgRTSEEyEgZTSEEyNTZK9AUtLS0tLUJFR0lOIENFUlRJRklD
      QVRFLS0tLS0KTUlJQ0F6Q0NBYWlnQXdJQkFnSVVPL3k3eno0ZWJBVVpRcUUyTm5Xb3hhaEsvYlV3
      Q2dZSUtvWkl6ajBFQXdJdwpYekVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2
      YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sd3dHZ1lE
      VlFRRERCTmpZUzVrY205dVpYTmxjblpwWTJVdGJtVjAKTUI0WERUSXhNRFl5T0RFNU1qSXlNMW9Y
      RFRJME1EUXhOekU1TWpJeU0xb3dYekVMTUFrR0ExVUVCaE1DUjBJeApEekFOQmdOVkJBZ01Ca3h2
      Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dU1SQXdEZ1lEVlFRS0RBZFBjbVJsCmNtVnlNUnd3
      R2dZRFZRUUREQk5qWVM1a2NtOXVaWE5sY25acFkyVXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUkK
      S29aSXpqMERBUWNEUWdBRU1WbVA0U2hselVIQ3dma0FKKzNvZUFULy83RGZtVlRJQThIdi92NmQ5
      SUs3eVZZaQpZUCtNb0JWWkVVTU1EdENYU3YvWVBMYXJpeVRPMThacEdYaUR1YU5DTUVBd0R3WURW
      UjBUQVFIL0JBVXdBd0VCCi96QU9CZ05WSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZHczZo
      WVY0bmgvWmRvSlNQNmFXM010anlaeEEKTUFvR0NDcUdTTTQ5QkFNQ0Ewa0FNRVlDSVFDQzF3REFh
      U2liZHRVSitRT3luOWFtb1hwL1o0V0tIemZQbTNmZAp1VU5iYWdJaEFMYThjMGcvMFZSdFhGSVZ2
      ZDlQZVZML25YZk5ZaW9DY0xIdE9TSWcxNFZZCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0aBkFk
      bWlucyI4CgdXcml0ZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPZHJvbmVzZXJ2aWNlTVNQGgZB
      ZG1pbnMiOQoGQWRtaW5zEi8SJQgBEiESCBIGCAESAggAGhUSEwoPZHJvbmVzZXJ2aWNlTVNQEAEa
      BkFkbWlucyI8CgtFbmRvcnNlbWVudBItEiMIARIfEggSBggBEgIIABoTEhEKD2Ryb25lc2Vydmlj
      ZU1TUBoGQWRtaW5zIjgKB1JlYWRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9kcm9uZXNlcnZp
      Y2VNU1AaBkFkbWlucyoGQWRtaW5zGh8KE0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRtaW5zGiQK
      DENhcGFiaWxpdGllcxIUEgoKCAoEVjFfMRIAGgZBZG1pbnMaxAEKDEthZmthQnJva2VycxKzARKo
      AQo2a2Fma2EtMC5icm9rZXIuZHJvbmVzZXJ2aWNlLW5ldC5zdmMuY2x1c3Rlci5sb2NhbDo5MDky
      CjZrYWZrYS0xLmJyb2tlci5kcm9uZXNlcnZpY2UtbmV0LnN2Yy5jbHVzdGVyLmxvY2FsOjkwOTIK
      NmthZmthLTIuYnJva2VyLmRyb25lc2VydmljZS1uZXQuc3ZjLmNsdXN0ZXIubG9jYWw6OTA5MhoG
      QWRtaW5zGiIKDUNvbnNlbnN1c1R5cGUSERIHCgVrYWZrYRoGQWRtaW5zGiIKCUJhdGNoU2l6ZRIV
      EgsIChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1pbnMiIgoH
      UmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0
      ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiKgoPQmxvY2tW
      YWxpZGF0aW9uEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5zEogwCgtDb25zb3J0aXVt
      cxL4LxKtLwoWRHJvbmVTZXJ2aWNlQ29uc29ydGl1bRKSLxK0LgoLY3VzdG9tZXJNU1ASpC4avCwK
      A01TUBK0LBKpLBKmLAoLY3VzdG9tZXJNU1AS7AUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0K
      TUlJQit6Q0NBYUtnQXdJQkFnSVVGdnNHMG5VVTM5SEFaT2VCTWVDWDczV29uZWd3Q2dZSUtvWkl6
      ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdB
      MVVFQnd3R1duVnlhV05vCk1SRXdEd1lEVlFRS0RBaERkWE4wYjIxbGNqRVlNQllHQTFVRUF3d1BZ
      MkV1WTNWemRHOXRaWEl0Ym1WME1CNFgKRFRJeE1EWXlPREU1TWpJeU9Gb1hEVEkwTURReE56RTVN
      akl5T0Zvd1hERUxNQWtHQTFVRUJoTUNRMGd4RHpBTgpCZ05WQkFnTUJscDFjbWxqYURFUE1BMEdB
      MVVFQnd3R1duVnlhV05vTVJFd0R3WURWUVFLREFoRGRYTjBiMjFsCmNqRVlNQllHQTFVRUF3d1BZ
      MkV1WTNWemRHOXRaWEl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMEQKQVFjRFFnQUVS
      NHVBTDJ6VjQvYkdFcXVmRXRWcWptcXFnRS8zWnNManhscXVWOWVLTDY0c012Q3FDaU96NHJlWgoz
      WHpudXBtVUF5MTcwUkxjVHNPM2hqd243a2VTbGFOQ01FQXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96
      QU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGSUd4NUF2ekpiVzhPMGFyRkNOWVRG
      elJoL1dHTUFvR0NDcUcKU000OUJBTUNBMGNBTUVRQ0h4UGlqcXRXc1kvMDBWQXhBRU1nODhFb2x1
      bmVnMFdvZnVqTUNGSHRUa2dDSVFDOApvdFFmM3lGZXZZOW4wL2V1VVhYWVJhbHpTWmNvbnE3UUtR
      T0lFeGNVT0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tIr0ILS0tLS1CRUdJTiBDRVJUSUZJ
      Q0FURS0tLS0tCk1JSUM5RENDQXBxZ0F3SUJBZ0lVRjJYWGxVOUtFNnEvMWY4SjdjT0F0Z09xTmow
      d0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21s
      amFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUkV3RHdZRFZRUUtEQWhEZFhOMGIyMWxjakVZTUJZ
      R0ExVUVBd3dQWTJFdVkzVnpkRzl0WlhJdGJtVjBNQjRYCkRUSXhNRFl5T0RFNU1qVXdNRm9YRFRJ
      eU1EWXlPREU1TXpBd01Gb3dlakVMTUFrR0ExVUVCaE1DUTBneEdqQVkKQmdOVkJBY1RFVFEzTGpN
      NEx6Z3VOVFF2V25WeWFXTm9NUkV3RHdZRFZRUUtFd2hEZFhOMGIyMWxjakVmTUF3RwpBMVVFQ3hN
      RllXUnRhVzR3RHdZRFZRUUxFd2hqZFhOMGIyMWxjakViTUJrR0ExVUVBd3dTUVdSdGFXNUFZM1Z6
      CmRHOXRaWEl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRWI1TDhpRzVt
      TzVBZ05HU3oKUXB1RHVyQnlCSkJHbE5kSTJ6R1BEcGk1TWcrTXR0V1Fjb3FXSTc0bXM1dGVQZXhZ
      ZzhCM3M2VHUwc2Vsekk1OQpRazJ3R2FPQ0FSb3dnZ0VXTUE0R0ExVWREd0VCL3dRRUF3SUhnREFN
      QmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkCkRnUVdCQlRmQVZpS0xCNWdrN0YyOUVPeHdIKzZ1Qkdj
      aHpBZkJnTlZIU01FR0RBV2dCU0JzZVFMOHlXMXZEdEcKcXhRaldFeGMwWWYxaGpBa0JnTlZIUkVF
      SFRBYmdobGpZUzEwYjI5c2N5MDNPRGRpTkdZNVptTmtMV0kzWjNwMApNSUdQQmdncUF3UUZCZ2NJ
      QVFTQmduc2lZWFIwY25NaU9uc2lZV0poWXk1cGJtbDBJam9pZEhKMVpTSXNJbUZrCmJXbHVJam9p
      ZEhKMVpTSXNJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lZM1Z6ZEc5dFpYSWlMQ0pvWmk1RmJuSnYK
      Ykd4dFpXNTBTVVFpT2lKQlpHMXBia0JqZFhOMGIyMWxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZ
      V1J0YVc0aQpmWDB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU9GUjZHM0FMZFd3NjlZNFh3d01n
      VDY5aWN5Vit0UjZzZ0pUCnQyT0V2V01GQWlCRlllcjVRK0tpUW92dyttSWJSTUU3QWRnREdpUVM3
      d3pHRmp3LzlKRWZqdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS1CDgoEU0hBMhIGU0hBMjU2
      SuwFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrekNDQWFLZ0F3SUJBZ0lVRnZzRzBu
      VVUzOUhBWk9lQk1lQ1g3M1dvbmVnd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1Ew
      Z3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUkV3RHdZRFZR
      UUtEQWhEZFhOMGIyMWxjakVZTUJZR0ExVUVBd3dQWTJFdVkzVnpkRzl0WlhJdGJtVjBNQjRYCkRU
      SXhNRFl5T0RFNU1qSXlPRm9YRFRJME1EUXhOekU1TWpJeU9Gb3dYREVMTUFrR0ExVUVCaE1DUTBn
      eER6QU4KQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdOb01SRXdEd1lEVlFR
      S0RBaERkWE4wYjIxbApjakVZTUJZR0ExVUVBd3dQWTJFdVkzVnpkRzl0WlhJdGJtVjBNRmt3RXdZ
      SEtvWkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFUjR1QUwyelY0L2JHRXF1ZkV0VnFqbXFxZ0Uv
      M1pzTGp4bHF1VjllS0w2NHNNdkNxQ2lPejRyZVoKM1h6bnVwbVVBeTE3MFJMY1RzTzNoanduN2tl
      U2xhTkNNRUF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFPQmdOVgpIUThCQWY4RUJBTUNBYVl3SFFZ
      RFZSME9CQllFRklHeDVBdnpKYlc4TzBhckZDTllURnpSaC9XR01Bb0dDQ3FHClNNNDlCQU1DQTBj
      QU1FUUNIeFBpanF0V3NZLzAwVkF4QUVNZzg4RW9sdW5lZzBXb2Z1ak1DRkh0VGtnQ0lRQzgKb3RR
      ZjN5RmV2WTluMC9ldVVYWFlSYWx6U1pjb25xN1FLUU9JRXhjVU9BPT0KLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLVroFwgBEvcFCuwFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrekND
      QWFLZ0F3SUJBZ0lVRnZzRzBuVVUzOUhBWk9lQk1lQ1g3M1dvbmVnd0NnWUlLb1pJemowRUF3SXcK
      WERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dX
      blZ5YVdObwpNUkV3RHdZRFZRUUtEQWhEZFhOMGIyMWxjakVZTUJZR0ExVUVBd3dQWTJFdVkzVnpk
      Rzl0WlhJdGJtVjBNQjRYCkRUSXhNRFl5T0RFNU1qSXlPRm9YRFRJME1EUXhOekU1TWpJeU9Gb3dY
      REVMTUFrR0ExVUVCaE1DUTBneER6QU4KQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dX
      blZ5YVdOb01SRXdEd1lEVlFRS0RBaERkWE4wYjIxbApjakVZTUJZR0ExVUVBd3dQWTJFdVkzVnpk
      Rzl0WlhJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFUjR1QUwyelY0
      L2JHRXF1ZkV0VnFqbXFxZ0UvM1pzTGp4bHF1VjllS0w2NHNNdkNxQ2lPejRyZVoKM1h6bnVwbVVB
      eTE3MFJMY1RzTzNoanduN2tlU2xhTkNNRUF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFPQmdOVgpI
      UThCQWY4RUJBTUNBYVl3SFFZRFZSME9CQllFRklHeDVBdnpKYlc4TzBhckZDTllURnpSaC9XR01B
      b0dDQ3FHClNNNDlCQU1DQTBjQU1FUUNIeFBpanF0V3NZLzAwVkF4QUVNZzg4RW9sdW5lZzBXb2Z1
      ak1DRkh0VGtnQ0lRQzgKb3RRZjN5RmV2WTluMC9ldVVYWFlSYWx6U1pjb25xN1FLUU9JRXhjVU9B
      PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLRIGY2xpZW50GvUFCuwFLS0tLS1CRUdJTiBDRVJU
      SUZJQ0FURS0tLS0tCk1JSUIrekNDQWFLZ0F3SUJBZ0lVRnZzRzBuVVUzOUhBWk9lQk1lQ1g3M1dv
      bmVnd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAx
      Y21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUkV3RHdZRFZRUUtEQWhEZFhOMGIyMWxjakVZ
      TUJZR0ExVUVBd3dQWTJFdVkzVnpkRzl0WlhJdGJtVjBNQjRYCkRUSXhNRFl5T0RFNU1qSXlPRm9Y
      RFRJME1EUXhOekU1TWpJeU9Gb3dYREVMTUFrR0ExVUVCaE1DUTBneER6QU4KQmdOVkJBZ01CbHAx
      Y21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdOb01SRXdEd1lEVlFRS0RBaERkWE4wYjIxbApjakVZ
      TUJZR0ExVUVBd3dQWTJFdVkzVnpkRzl0WlhJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6
      ajBECkFRY0RRZ0FFUjR1QUwyelY0L2JHRXF1ZkV0VnFqbXFxZ0UvM1pzTGp4bHF1VjllS0w2NHNN
      dkNxQ2lPejRyZVoKM1h6bnVwbVVBeTE3MFJMY1RzTzNoanduN2tlU2xhTkNNRUF3RHdZRFZSMFRB
      UUgvQkFVd0F3RUIvekFPQmdOVgpIUThCQWY4RUJBTUNBYVl3SFFZRFZSME9CQllFRklHeDVBdnpK
      Ylc4TzBhckZDTllURnpSaC9XR01Bb0dDQ3FHClNNNDlCQU1DQTBjQU1FUUNIeFBpanF0V3NZLzAw
      VkF4QUVNZzg4RW9sdW5lZzBXb2Z1ak1DRkh0VGtnQ0lRQzgKb3RRZjN5RmV2WTluMC9ldVVYWFlS
      YWx6U1pjb25xN1FLUU9JRXhjVU9BPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLRIEcGVlciL2
      BQrsBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK3pDQ0FhS2dBd0lCQWdJVUZ2c0cw
      blVVMzlIQVpPZUJNZUNYNzNXb25lZ3dDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNR
      MGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJFd0R3WURW
      UVFLREFoRGRYTjBiMjFsY2pFWU1CWUdBMVVFQXd3UFkyRXVZM1Z6ZEc5dFpYSXRibVYwTUI0WApE
      VEl4TURZeU9ERTVNakl5T0ZvWERUSTBNRFF4TnpFNU1qSXlPRm93WERFTE1Ba0dBMVVFQmhNQ1Ew
      Z3hEekFOCkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm9NUkV3RHdZRFZR
      UUtEQWhEZFhOMGIyMWwKY2pFWU1CWUdBMVVFQXd3UFkyRXVZM1Z6ZEc5dFpYSXRibVYwTUZrd0V3
      WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRVI0dUFMMnpWNC9iR0VxdWZFdFZxam1xcWdF
      LzNac0xqeGxxdVY5ZUtMNjRzTXZDcUNpT3o0cmVaCjNYem51cG1VQXkxNzBSTGNUc08zaGp3bjdr
      ZVNsYU5DTUVBd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hR
      WURWUjBPQkJZRUZJR3g1QXZ6SmJXOE8wYXJGQ05ZVEZ6UmgvV0dNQW9HQ0NxRwpTTTQ5QkFNQ0Ew
      Y0FNRVFDSHhQaWpxdFdzWS8wMFZBeEFFTWc4OEVvbHVuZWcwV29mdWpNQ0ZIdFRrZ0NJUUM4Cm90
      UWYzeUZldlk5bjAvZXVVWFhZUmFselNaY29ucTdRS1FPSUV4Y1VPQT09Ci0tLS0tRU5EIENFUlRJ
      RklDQVRFLS0tLS0SBWFkbWluKvgFCuwFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIr
      ekNDQWFLZ0F3SUJBZ0lVRnZzRzBuVVUzOUhBWk9lQk1lQ1g3M1dvbmVnd0NnWUlLb1pJemowRUF3
      SXcKWERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3
      d0dXblZ5YVdObwpNUkV3RHdZRFZRUUtEQWhEZFhOMGIyMWxjakVZTUJZR0ExVUVBd3dQWTJFdVkz
      VnpkRzl0WlhJdGJtVjBNQjRYCkRUSXhNRFl5T0RFNU1qSXlPRm9YRFRJME1EUXhOekU1TWpJeU9G
      b3dYREVMTUFrR0ExVUVCaE1DUTBneER6QU4KQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3
      d0dXblZ5YVdOb01SRXdEd1lEVlFRS0RBaERkWE4wYjIxbApjakVZTUJZR0ExVUVBd3dQWTJFdVkz
      VnpkRzl0WlhJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFUjR1QUwy
      elY0L2JHRXF1ZkV0VnFqbXFxZ0UvM1pzTGp4bHF1VjllS0w2NHNNdkNxQ2lPejRyZVoKM1h6bnVw
      bVVBeTE3MFJMY1RzTzNoanduN2tlU2xhTkNNRUF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFPQmdO
      VgpIUThCQWY4RUJBTUNBYVl3SFFZRFZSME9CQllFRklHeDVBdnpKYlc4TzBhckZDTllURnpSaC9X
      R01Bb0dDQ3FHClNNNDlCQU1DQTBjQU1FUUNIeFBpanF0V3NZLzAwVkF4QUVNZzg4RW9sdW5lZzBX
      b2Z1ak1DRkh0VGtnQ0lRQzgKb3RRZjN5RmV2WTluMC9ldVVYWFlSYWx6U1pjb25xN1FLUU9JRXhj
      VU9BPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLRIHb3JkZXJlchoGQWRtaW5zIjUKBkFkbWlu
      cxIrEiEIARIdEggSBggBEgIIABoREg8KC2N1c3RvbWVyTVNQEAEaBkFkbWlucyI4CgtFbmRvcnNl
      bWVudBIpEh8IARIbEggSBggBEgIIABoPEg0KC2N1c3RvbWVyTVNQGgZBZG1pbnMiNAoHUmVhZGVy
      cxIpEh8IARIbEggSBggBEgIIABoPEg0KC2N1c3RvbWVyTVNQGgZBZG1pbnMiNAoHV3JpdGVycxIp
      Eh8IARIbEggSBggBEgIIABoPEg0KC2N1c3RvbWVyTVNQGgZBZG1pbnMqBkFkbWlucxpAChVDaGFu
      bmVsQ3JlYXRpb25Qb2xpY3kSJxIMCAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlu
      cyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hhbm5l
      bC9PcmRlcmVyL0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoQSGFzaGluZ0FsZ29y
      aXRobRISEggKBlNIQTI1NhoGQWRtaW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUSEBIG
      CP////8PGgZBZG1pbnMaTwoQT3JkZXJlckFkZHJlc3NlcxI7EiAKHm9yZGVyZXIxLmRyb25lc2Vy
      dmljZS1uZXQ6NzA1MBoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJAoMQ2FwYWJpbGl0aWVzEhQS
      CgoICgRWMV8xEgAaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIi
      CgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1Jl
      YWRlcnMaBkFkbWlucyoGQWRtaW5zGgoKAAoACgAKAAoA
