apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: droneservice-orderer1
  namespace: droneservice-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: droneservice-orderer1
  chart:
    git: https://github.com/MChorfa/blockchain-automation-framework.git
    ref: local
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: droneservice-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.0
        alpineutils: hyperledgerlabs/alpine-utils:1.0

    orderer:
      name: orderer1
      loglevel: info
      localmspid: droneserviceMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: kafka

    storage:
      storageclassname: droneservicesc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.2.121:8200
      role: vault-role
      authpath: localdroneservice-net-auth
      secretprefix: secret/crypto/ordererOrganizations/droneservice-net/orderers/orderer1.droneservice-net
      imagesecretname: regcred
      serviceaccountname: vault-auth
    kafka:
      readinesscheckinterval: 10
      readinessthreshold: 10
      brokers:
      - kafka-0.broker.droneservice-net.svc.cluster.local:9092
      - kafka-1.broker.droneservice-net.svc.cluster.local:9092
      - kafka-2.broker.droneservice-net.svc.cluster.local:9092

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIFn2LdTDVaKxOPeZ7SAKUJ3B+BfkGrc2vhkk7qJr76hoEuFOCt5OCttOCngKWggBEAEaBgjg
      2+mGBiIKc3lzY2hhbm5lbCpAMzk4NWE3ZTI4ZWExNmJkZWEzODkyZWU3MTBkYzdiNTRiZjhmMGQ2
      M2NkNTk4ZTkwZjQ1MjdjMmIzN2UyODIyORIaEhicN4sq+gHqGM3vSCO6/NHgX+b9q2HnxZ8S3k0K
      200S2E0SizAKC0NvbnNvcnRpdW1zEvsvErAvChZEcm9uZVNlcnZpY2VDb25zb3J0aXVtEpUvErcu
      CgtjdXN0b21lck1TUBKnLhq/LAoDTVNQErcsEqwsEqksCgtjdXN0b21lck1TUBLtBS0tLS0tQkVH
      SU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCL0RDQ0FhS2dBd0lCQWdJVVZRdUVzeW5NM3dVZTEyWmYx
      VVRvTWhnNWFRVXdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZC
      QWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFoRGRYTjBi
      MjFsY2pFWU1CWUdBMVVFQXd3UFkyRXVZM1Z6ZEc5dFpYSXRibVYwTUI0WApEVEl4TURZeU9UQXdN
      emsxTWxvWERUSTBNRFF4T0RBd016azFNbG93WERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOCkJnTlZC
      QWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm9NUkV3RHdZRFZRUUtEQWhEZFhOMGIy
      MWwKY2pFWU1CWUdBMVVFQXd3UFkyRXVZM1Z6ZEc5dFpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FR
      WUlLb1pJemowRApBUWNEUWdBRS9vWnJYWWxuOER0blVJR0lleUkwemsxSEgxT2o2MjYzV1J1a1dW
      ZFZZYkl6VEM1MzBpdzl2eklMClNwbTJ4MEtJYkZXNXVOU2g4RDhKN1FPYURTenIyS05DTUVBd0R3
      WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZB
      WkR4VDIwVk1RMHdLM1hkOHZaNzhYZUJYMHhNQW9HQ0NxRwpTTTQ5QkFNQ0EwZ0FNRVVDSUZ3b0o1
      OEdlMitxTEtiNzNRUXNsckhEZXpab0dJNnUxQ25tZDQzOHRtRHlBaUVBCndrbEJUc2g0MkVnK2lR
      UzByVnBobS9YVmIwMzFMZWNWa3hIcE1hNUIrZzA9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      IroILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4ekNDQXBxZ0F3SUJBZ0lVWUMvb29z
      M0tmK1RrVFd5NmJDS29lWEtDL2tnd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1Ew
      Z3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUkV3RHdZRFZR
      UUtEQWhEZFhOMGIyMWxjakVZTUJZR0ExVUVBd3dQWTJFdVkzVnpkRzl0WlhJdGJtVjBNQjRYCkRU
      SXhNRFl5T1RBd05ETXdNRm9YRFRJeU1EWXlPVEF3TkRnd01Gb3dlakVMTUFrR0ExVUVCaE1DUTBn
      eEdqQVkKQmdOVkJBY1RFVFEzTGpNNEx6Z3VOVFF2V25WeWFXTm9NUkV3RHdZRFZRUUtFd2hEZFhO
      MGIyMWxjakVmTUF3RwpBMVVFQ3hNRllXUnRhVzR3RHdZRFZRUUxFd2hqZFhOMGIyMWxjakViTUJr
      R0ExVUVBd3dTUVdSdGFXNUFZM1Z6CmRHOXRaWEl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29a
      SXpqMERBUWNEUWdBRTNVSDBGejFHcHlTUGpTK0IKMm1kVENoRWlBTVhBa05hRjEyTlVldFIzRnU3
      QlFpdmxETjJ5aE9tTU1UWGJtMmxrOCtMVUEvSUhTaktsVDdPTAp0UFZNcHFPQ0FSb3dnZ0VXTUE0
      R0ExVWREd0VCL3dRRUF3SUhnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkCkRnUVdCQlNFTk1w
      L0grMVZRSlhIejV1VDBCbFBWNnlGRURBZkJnTlZIU01FR0RBV2dCUUdROFU5dEZURU5NQ3QKMTNm
      TDJlL0YzZ1Y5TVRBa0JnTlZIUkVFSFRBYmdobGpZUzEwYjI5c2N5MDNPRGRpTkdZNVptTmtMWEZx
      ZHpWcQpNSUdQQmdncUF3UUZCZ2NJQVFTQmduc2lZWFIwY25NaU9uc2lZV0poWXk1cGJtbDBJam9p
      ZEhKMVpTSXNJbUZrCmJXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lZM1Z6
      ZEc5dFpYSWlMQ0pvWmk1RmJuSnYKYkd4dFpXNTBTVVFpT2lKQlpHMXBia0JqZFhOMGIyMWxjaTF1
      WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aQpmWDB3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUln
      RVQyRGIyWGdwaTBiUTBvMkJLNzJPUkNObDc0N0I0L2tOdWRvCkd1QS9McndDSUJmOWEzY0ExKyt6
      MEpuUk92QmpYNUNuUU5GamZwLzNwRFoyZ3BzaS9YMmwKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQpCDgoEU0hBMhIGU0hBMjU2Su0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvREND
      QWFLZ0F3SUJBZ0lVVlF1RXN5bk0zd1VlMTJaZjFVVG9NaGc1YVFVd0NnWUlLb1pJemowRUF3SXcK
      WERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dX
      blZ5YVdObwpNUkV3RHdZRFZRUUtEQWhEZFhOMGIyMWxjakVZTUJZR0ExVUVBd3dQWTJFdVkzVnpk
      Rzl0WlhJdGJtVjBNQjRYCkRUSXhNRFl5T1RBd016azFNbG9YRFRJME1EUXhPREF3TXprMU1sb3dY
      REVMTUFrR0ExVUVCaE1DUTBneER6QU4KQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dX
      blZ5YVdOb01SRXdEd1lEVlFRS0RBaERkWE4wYjIxbApjakVZTUJZR0ExVUVBd3dQWTJFdVkzVnpk
      Rzl0WlhJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFL29aclhZbG44
      RHRuVUlHSWV5STB6azFISDFPajYyNjNXUnVrV1ZkVlliSXpUQzUzMGl3OXZ6SUwKU3BtMngwS0li
      Rlc1dU5TaDhEOEo3UU9hRFN6cjJLTkNNRUF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFPQmdOVgpI
      UThCQWY4RUJBTUNBYVl3SFFZRFZSME9CQllFRkFaRHhUMjBWTVEwd0szWGQ4dlo3OFhlQlgweE1B
      b0dDQ3FHClNNNDlCQU1DQTBnQU1FVUNJRndvSjU4R2UyK3FMS2I3M1FRc2xySERlelpvR0k2dTFD
      bm1kNDM4dG1EeUFpRUEKd2tsQlRzaDQyRWcraVFTMHJWcGhtL1hWYjAzMUxlY1ZreEhwTWE1Qitn
      MD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpa7BcIARL4BQrtBS0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlCL0RDQ0FhS2dBd0lCQWdJVVZRdUVzeW5NM3dVZTEyWmYxVVRvTWhnNWFR
      VXdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNt
      bGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFoRGRYTjBiMjFsY2pFWU1C
      WUdBMVVFQXd3UFkyRXVZM1Z6ZEc5dFpYSXRibVYwTUI0WApEVEl4TURZeU9UQXdNemsxTWxvWERU
      STBNRFF4T0RBd016azFNbG93WERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOCkJnTlZCQWdNQmxwMWNt
      bGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm9NUkV3RHdZRFZRUUtEQWhEZFhOMGIyMWwKY2pFWU1C
      WUdBMVVFQXd3UFkyRXVZM1Z6ZEc5dFpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemow
      RApBUWNEUWdBRS9vWnJYWWxuOER0blVJR0lleUkwemsxSEgxT2o2MjYzV1J1a1dWZFZZYkl6VEM1
      MzBpdzl2eklMClNwbTJ4MEtJYkZXNXVOU2g4RDhKN1FPYURTenIyS05DTUVBd0R3WURWUjBUQVFI
      L0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZBWkR4VDIwVk1R
      MHdLM1hkOHZaNzhYZUJYMHhNQW9HQ0NxRwpTTTQ5QkFNQ0EwZ0FNRVVDSUZ3b0o1OEdlMitxTEti
      NzNRUXNsckhEZXpab0dJNnUxQ25tZDQzOHRtRHlBaUVBCndrbEJUc2g0MkVnK2lRUzByVnBobS9Y
      VmIwMzFMZWNWa3hIcE1hNUIrZzA9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEgZjbGllbnQa
      9gUK7QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQi9EQ0NBYUtnQXdJQkFnSVVWUXVF
      c3luTTN3VWUxMlpmMVVUb01oZzVhUVV3Q2dZSUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1D
      UTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SRXdEd1lE
      VlFRS0RBaERkWE4wYjIxbGNqRVlNQllHQTFVRUF3d1BZMkV1WTNWemRHOXRaWEl0Ym1WME1CNFgK
      RFRJeE1EWXlPVEF3TXprMU1sb1hEVEkwTURReE9EQXdNemsxTWxvd1hERUxNQWtHQTFVRUJoTUNR
      MGd4RHpBTgpCZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vTVJFd0R3WURW
      UVFLREFoRGRYTjBiMjFsCmNqRVlNQllHQTFVRUF3d1BZMkV1WTNWemRHOXRaWEl0Ym1WME1Ga3dF
      d1lIS29aSXpqMENBUVlJS29aSXpqMEQKQVFjRFFnQUUvb1pyWFlsbjhEdG5VSUdJZXlJMHprMUhI
      MU9qNjI2M1dSdWtXVmRWWWJJelRDNTMwaXc5dnpJTApTcG0yeDBLSWJGVzV1TlNoOEQ4SjdRT2FE
      U3pyMktOQ01FQXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdI
      UVlEVlIwT0JCWUVGQVpEeFQyMFZNUTB3SzNYZDh2Wjc4WGVCWDB4TUFvR0NDcUcKU000OUJBTUNB
      MGdBTUVVQ0lGd29KNThHZTIrcUxLYjczUVFzbHJIRGV6Wm9HSTZ1MUNubWQ0Mzh0bUR5QWlFQQp3
      a2xCVHNoNDJFZytpUVMwclZwaG0vWFZiMDMxTGVjVmt4SHBNYTVCK2cwPQotLS0tLUVORCBDRVJU
      SUZJQ0FURS0tLS0tChIEcGVlciL3BQrtBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlC
      L0RDQ0FhS2dBd0lCQWdJVVZRdUVzeW5NM3dVZTEyWmYxVVRvTWhnNWFRVXdDZ1lJS29aSXpqMEVB
      d0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVC
      d3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFoRGRYTjBiMjFsY2pFWU1CWUdBMVVFQXd3UFkyRXVZ
      M1Z6ZEc5dFpYSXRibVYwTUI0WApEVEl4TURZeU9UQXdNemsxTWxvWERUSTBNRFF4T0RBd016azFN
      bG93WERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOCkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVC
      d3dHV25WeWFXTm9NUkV3RHdZRFZRUUtEQWhEZFhOMGIyMWwKY2pFWU1CWUdBMVVFQXd3UFkyRXVZ
      M1Z6ZEc5dFpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRS9vWnJY
      WWxuOER0blVJR0lleUkwemsxSEgxT2o2MjYzV1J1a1dWZFZZYkl6VEM1MzBpdzl2eklMClNwbTJ4
      MEtJYkZXNXVOU2g4RDhKN1FPYURTenIyS05DTUVBd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0Jn
      TlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZBWkR4VDIwVk1RMHdLM1hkOHZaNzhYZUJY
      MHhNQW9HQ0NxRwpTTTQ5QkFNQ0EwZ0FNRVVDSUZ3b0o1OEdlMitxTEtiNzNRUXNsckhEZXpab0dJ
      NnUxQ25tZDQzOHRtRHlBaUVBCndrbEJUc2g0MkVnK2lRUzByVnBobS9YVmIwMzFMZWNWa3hIcE1h
      NUIrZzA9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEgVhZG1pbir5BQrtBS0tLS0tQkVHSU4g
      Q0VSVElGSUNBVEUtLS0tLQpNSUlCL0RDQ0FhS2dBd0lCQWdJVVZRdUVzeW5NM3dVZTEyWmYxVVRv
      TWhnNWFRVXdDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdN
      QmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJFd0R3WURWUVFLREFoRGRYTjBiMjFs
      Y2pFWU1CWUdBMVVFQXd3UFkyRXVZM1Z6ZEc5dFpYSXRibVYwTUI0WApEVEl4TURZeU9UQXdNemsx
      TWxvWERUSTBNRFF4T0RBd016azFNbG93WERFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOCkJnTlZCQWdN
      QmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm9NUkV3RHdZRFZRUUtEQWhEZFhOMGIyMWwK
      Y2pFWU1CWUdBMVVFQXd3UFkyRXVZM1Z6ZEc5dFpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlL
      b1pJemowRApBUWNEUWdBRS9vWnJYWWxuOER0blVJR0lleUkwemsxSEgxT2o2MjYzV1J1a1dWZFZZ
      Ykl6VEM1MzBpdzl2eklMClNwbTJ4MEtJYkZXNXVOU2g4RDhKN1FPYURTenIyS05DTUVBd0R3WURW
      UjBUQVFIL0JBVXdBd0VCL3pBT0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZBWkR4
      VDIwVk1RMHdLM1hkOHZaNzhYZUJYMHhNQW9HQ0NxRwpTTTQ5QkFNQ0EwZ0FNRVVDSUZ3b0o1OEdl
      MitxTEtiNzNRUXNsckhEZXpab0dJNnUxQ25tZDQzOHRtRHlBaUVBCndrbEJUc2g0MkVnK2lRUzBy
      VnBobS9YVmIwMzFMZWNWa3hIcE1hNUIrZzA9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEgdv
      cmRlcmVyGgZBZG1pbnMiNQoGQWRtaW5zEisSIQgBEh0SCBIGCAESAggAGhESDwoLY3VzdG9tZXJN
      U1AQARoGQWRtaW5zIjgKC0VuZG9yc2VtZW50EikSHwgBEhsSCBIGCAESAggAGg8SDQoLY3VzdG9t
      ZXJNU1AaBkFkbWlucyI0CgdSZWFkZXJzEikSHwgBEhsSCBIGCAESAggAGg8SDQoLY3VzdG9tZXJN
      U1AaBkFkbWlucyI0CgdXcml0ZXJzEikSHwgBEhsSCBIGCAESAggAGg8SDQoLY3VzdG9tZXJNU1Aa
      BkFkbWlucyoGQWRtaW5zGkAKFUNoYW5uZWxDcmVhdGlvblBvbGljeRInEgwIAxIICgZBZG1pbnMa
      Fy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyItCgZBZG1p
      bnMSIxIICAESBBICEgAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVy
      L0FkbWlucxKFGwoHT3JkZXJlchL5GhLgFgoPZHJvbmVzZXJ2aWNlTVNQEswWGtQUCgNNU1ASzBQS
      wRQSvhQKD2Ryb25lc2VydmljZU1TUBL1BS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlD
      QXpDQ0FhaWdBd0lCQWdJVUlSOGRDRlhxU09RQWVPRGxldytCUzNMTDU4d3dDZ1lJS29aSXpqMEVB
      d0l3Clh6RUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVC
      d3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJ3d0dnWURWUVFEREJOallTNWtj
      bTl1WlhObGNuWnBZMlV0Ym1WMApNQjRYRFRJeE1EWXlPVEF3TXprME4xb1hEVEkwTURReE9EQXdN
      emswTjFvd1h6RUxNQWtHQTFVRUJoTUNSMEl4CkR6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdB
      MVVFQnd3R1RHOXVaRzl1TVJBd0RnWURWUVFLREFkUGNtUmwKY21WeU1Sd3dHZ1lEVlFRRERCTmpZ
      UzVrY205dVpYTmxjblpwWTJVdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSQpLb1pJemowREFRY0RR
      Z0FFR25aTTJ4Skk5bUR3TEhEVWYxTTM2cGFla3p6ZG8zRmt3R2srOHpFSVNaOG1MVnhCCnN1M0k2
      K0JaY3ZwREkzc3BjNGpiZ3EyNHVLZ2ZRVC90dkp0ZFRxTkNNRUF3RHdZRFZSMFRBUUgvQkFVd0F3
      RUIKL3pBT0JnTlZIUThCQWY4RUJBTUNBYVl3SFFZRFZSME9CQllFRkthb1BYd2NpMTVJa1NSbGRX
      bENJNFF3VW1rVgpNQW9HQ0NxR1NNNDlCQU1DQTBrQU1FWUNJUUQ3eFZNSDlvN0F5aHlFc2xWWkZn
      bDRBRmx4dUc2WnlyYlZpdHRoClVOVVFKQUloQU5HUCtYdFRhREdWYW9aV0d3WVVaMWpjTEFSVW10
      SGpEemx4THdsVUhEWGsKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoiqggtLS0tLUJFR0lOIENF
      UlRJRklDQVRFLS0tLS0KTUlJQzVUQ0NBb3VnQXdJQkFnSVVjY3hUcE56QndMVWUwTlE0SnRKWVZv
      SWxnSkl3Q2dZSUtvWkl6ajBFQXdJdwpYekVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJr
      eHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1S
      d3dHZ1lEVlFRRERCTmpZUzVrY205dVpYTmxjblpwWTJVdGJtVjAKTUI0WERUSXhNRFl5T1RBd05E
      TXdNRm9YRFRJeU1EWXlPVEF3TkRnd01Gb3diVEVMTUFrR0ExVUVCaE1DUjBJeApHekFaQmdOVkJB
      Y1RFalV4TGpVd0x5MHdMakV6TDB4dmJtUnZiakVRTUE0R0ExVUVDaE1IVDNKa1pYSmxjakVPCk1B
      d0dBMVVFQ3hNRllXUnRhVzR4SHpBZEJnTlZCQU1NRmtGa2JXbHVRR1J5YjI1bGMyVnlkbWxqWlMx
      dVpYUXcKV1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVFQb29pZW1kS3VVa2xKcGs0
      Y1pOdDJ3RFBlbkJlYQoxZDNSb21vY1ZtSG1zcmtWRWF3TVBONitnMlVraE5mMGYxdi9iQ0JyNW1E
      VGJYWm9uNG5kZEwrUm80SUJGVENDCkFSRXdEZ1lEVlIwUEFRSC9CQVFEQWdlQU1Bd0dBMVVkRXdF
      Qi93UUNNQUF3SFFZRFZSME9CQllFRkt1cGZQTWgKNUNqQllGaHUzSnhkYUZFNUtvUFFNQjhHQTFV
      ZEl3UVlNQmFBRkthb1BYd2NpMTVJa1NSbGRXbENJNFF3VW1rVgpNQ1FHQTFVZEVRUWRNQnVDR1dO
      aExYUnZiMnh6TFRjNE4ySTBaamxtWTJRdGJYSjNNbkV3Z1lvR0NDb0RCQVVHCkJ3Z0JCSDU3SW1G
      MGRISnpJanA3SW1GaVlXTXVhVzVwZENJNkluUnlkV1VpTENKaFpHMXBiaUk2SW5SeWRXVWkKTENK
      b1ppNUJabVpwYkdsaGRHbHZiaUk2SWlJc0ltaG1Ma1Z1Y205c2JHMWxiblJKUkNJNklrRmtiV2x1
      UUdSeQpiMjVsYzJWeWRtbGpaUzF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJ
      S29aSXpqMEVBd0lEClNBQXdSUUloQUx2UkdoVk1pYnB4K21XNWZlWC8zNm1UMGdJRitNSjcyRGR6
      YkVtWm5vYmpBaUJXOTlDbndQVlAKR0VxS2tzdUkvcm5pZ0drL21wMEt1SFRBWTlrdW1sOEo3Zz09
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1Nkr1BS0tLS0tQkVHSU4g
      Q0VSVElGSUNBVEUtLS0tLQpNSUlDQXpDQ0FhaWdBd0lCQWdJVUlSOGRDRlhxU09RQWVPRGxldytC
      UzNMTDU4d3dDZ1lJS29aSXpqMEVBd0l3Clh6RUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdN
      Qmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5
      TVJ3d0dnWURWUVFEREJOallTNWtjbTl1WlhObGNuWnBZMlV0Ym1WMApNQjRYRFRJeE1EWXlPVEF3
      TXprME4xb1hEVEkwTURReE9EQXdNemswTjFvd1h6RUxNQWtHQTFVRUJoTUNSMEl4CkR6QU5CZ05W
      QkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1TVJBd0RnWURWUVFLREFkUGNtUmwK
      Y21WeU1Sd3dHZ1lEVlFRRERCTmpZUzVrY205dVpYTmxjblpwWTJVdGJtVjBNRmt3RXdZSEtvWkl6
      ajBDQVFZSQpLb1pJemowREFRY0RRZ0FFR25aTTJ4Skk5bUR3TEhEVWYxTTM2cGFla3p6ZG8zRmt3
      R2srOHpFSVNaOG1MVnhCCnN1M0k2K0JaY3ZwREkzc3BjNGpiZ3EyNHVLZ2ZRVC90dkp0ZFRxTkNN
      RUF3RHdZRFZSMFRBUUgvQkFVd0F3RUIKL3pBT0JnTlZIUThCQWY4RUJBTUNBYVl3SFFZRFZSME9C
      QllFRkthb1BYd2NpMTVJa1NSbGRXbENJNFF3VW1rVgpNQW9HQ0NxR1NNNDlCQU1DQTBrQU1FWUNJ
      UUQ3eFZNSDlvN0F5aHlFc2xWWkZnbDRBRmx4dUc2WnlyYlZpdHRoClVOVVFKQUloQU5HUCtYdFRh
      REdWYW9aV0d3WVVaMWpjTEFSVW10SGpEemx4THdsVUhEWGsKLS0tLS1FTkQgQ0VSVElGSUNBVEUt
      LS0tLQoaBkFkbWlucyI5CgZBZG1pbnMSLxIlCAESIRIIEgYIARICCAAaFRITCg9kcm9uZXNlcnZp
      Y2VNU1AQARoGQWRtaW5zIjwKC0VuZG9yc2VtZW50Ei0SIwgBEh8SCBIGCAESAggAGhMSEQoPZHJv
      bmVzZXJ2aWNlTVNQGgZBZG1pbnMiOAoHUmVhZGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD2Ry
      b25lc2VydmljZU1TUBoGQWRtaW5zIjgKB1dyaXRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9k
      cm9uZXNlcnZpY2VNU1AaBkFkbWlucyoGQWRtaW5zGiIKDUNvbnNlbnN1c1R5cGUSERIHCgVrYWZr
      YRoGQWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGlt
      ZW91dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMaJAoM
      Q2FwYWJpbGl0aWVzEhQSCgoICgRWMl8wEgAaBkFkbWlucxrEAQoMS2Fma2FCcm9rZXJzErMBEqgB
      CjZrYWZrYS0wLmJyb2tlci5kcm9uZXNlcnZpY2UtbmV0LnN2Yy5jbHVzdGVyLmxvY2FsOjkwOTIK
      NmthZmthLTEuYnJva2VyLmRyb25lc2VydmljZS1uZXQuc3ZjLmNsdXN0ZXIubG9jYWw6OTA5Mgo2
      a2Fma2EtMi5icm9rZXIuZHJvbmVzZXJ2aWNlLW5ldC5zdmMuY2x1c3Rlci5sb2NhbDo5MDkyGgZB
      ZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgdSZWFk
      ZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMa
      BkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyoGQWRtaW5zGiYKEEhh
      c2hpbmdBbGdvcml0aG0SEhIICgZTSEEyNTYaBkFkbWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3Ry
      dWN0dXJlEhASBgj/////DxoGQWRtaW5zGk8KEE9yZGVyZXJBZGRyZXNzZXMSOxIgCh5vcmRlcmVy
      MS5kcm9uZXNlcnZpY2UtbmV0OjcwNTAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiQKDENhcGFi
      aWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxAC
      GgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIX
      Eg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFkbWlucxoOCgQKAgoACgAKAAoACgA=
